### ISSUE TITLE
Add merge pull request commands

### ISSUE THREAD

**Issue by IonicaBizau** [Toddsqui/learning-git#1]
Switch on master, merge, push.

**Comment by IonicaBizau** [comment]
Replace the [TODO, here](https://github.com/Toddsqui/learning-git#github-pull-requests).

**Comment by Toddsqui** [comment]
:book: 

@IonicaBizau Please check out the changes I made! I think I did this correctly!

**Comment by IonicaBizau** [comment]
@Toddsqui Great! :sparkles: 

I would recommend putting these commands into a single code block (```` ```sh ````) in the 3rd point from [Github Pull Requests](https://github.com/Toddsqui/learning-git#github-pull-requests).

Also, before editing, create a new branch, make this edit, commit the changes and push the branch on GitHub. Then create a pull request and ping me.

:bulb: After pushing the branch on GitHub (`git push --all`) you will notice a create pull request button in the repository.

**Comment by Toddsqui** [comment]
@IonicaBizau We finished this issue! :sunglasses:

**Comment by IonicaBizau** [comment]
:cool:
