### ISSUE TITLE
How to list branches?

### ISSUE THREAD

**Issue by IonicaBizau** [Toddsqui/learning-git#2]
Add the command for listing branches :thought_balloon:

**Comment by IonicaBizau** [comment]
Add a *List branches in the current repo* [here](https://github.com/Toddsqui/learning-git#using-git-branches-and-github-pull-requests) and the command to list the branches.

Create a new branch (`git checkout -b list-branches`), commit the changes and push the branch on GitHub (`git push --all`) then you will see a big green button for creating a pull request. Ping me in the pull request description. :balloon:

**Comment by Toddsqui** [comment]
@IonicaBizau  We closed the issue! :smile:

**Comment by IonicaBizau** [comment]
:rocket:
